// Copyright 2026 The aterm Authors
// SPDX-License-Identifier: Apache-2.0

//! Lattice operations: type-level [`JoinWith`], [`SelfSameOrigin`],
//! [`OriginsCompatible`], and their runtime mirrors ([`runtime_join`],
//! [`dominates`], and the `Option`-lifted [`join`] helper).
//!
//! The 36 [`JoinWith`] impls and the dominance-derived [`OriginsCompatible`]
//! impls are generated by `build.rs` from the single-source-of-truth matrix
//! in `designs/2026-04-19-provenance-framework.md` §3.1.

use crate::origin::{Ai, ConfigFile, Host, NetworkUntrusted, Origin, OriginTag, Pty, User};

/// Type-level join. `<A as JoinWith<B>>::Output` is the "wider" of `A` and
/// `B` per the lattice in §3.1.
///
/// The 36 impls are generated by `build.rs` from a single-source-of-truth
/// matrix; see that file for the table.
pub trait JoinWith<Rhs: Origin>: Origin {
    /// The joined origin (the "wider"/"more dilute" of `Self` and `Rhs`).
    type Output: Origin;
}

/// Marker trait implemented exactly when `Self == Other` as origins.
///
/// A sink that requires *exactly* a given origin (rather than "at most")
/// bounds its parameter by `SelfSameOrigin<RequiredOrigin>`.
pub trait SelfSameOrigin<Other: Origin>: Origin {}

impl SelfSameOrigin<Host> for Host {}
impl SelfSameOrigin<ConfigFile> for ConfigFile {}
impl SelfSameOrigin<User> for User {}
impl SelfSameOrigin<Ai> for Ai {}
impl SelfSameOrigin<NetworkUntrusted> for NetworkUntrusted {}
impl SelfSameOrigin<Pty> for Pty {}

/// Marker trait implemented when `Self` dominates `Required` in the lattice
/// (i.e., `Self` is as trusted as or more trusted than `Required`).
///
/// Sinks bound their parameter by `OriginsCompatible<RequiredOrigin>` to
/// accept values from any origin that dominates `RequiredOrigin`.
///
/// ```text
/// fn clipboard_write<O>(body: Provenance<&str, O>)
/// where
///     O: OriginsCompatible<User>,  // User, ConfigFile, Host satisfy;
///                                  // Ai / NetworkUntrusted / Pty reject.
/// { /* ... */ }
/// ```
pub trait OriginsCompatible<Required: Origin>: Origin {}

// `JoinWith` and `OriginsCompatible` impls are generated by build.rs from the
// §3.1 table. See `build.rs`.
include!(concat!(env!("OUT_DIR"), "/join_table.rs"));

// ---------------------------------------------------------------------------
// Runtime lattice operations (mirror of the type-level JoinWith table)
// ---------------------------------------------------------------------------

/// Runtime join of two [`OriginTag`]s. Always resolves to a concrete
/// [`OriginTag`] per §3.1 (the 6-element lattice has no `Top`-yielding
/// pairs when both operands are concrete tags; `Top` is synthetic, see §3.2).
///
/// ```
/// use aterm_provenance::{runtime_join, OriginTag};
/// assert_eq!(runtime_join(OriginTag::Host, OriginTag::Pty), OriginTag::Pty);
/// assert_eq!(runtime_join(OriginTag::User, OriginTag::Ai), OriginTag::Ai);
/// assert_eq!(runtime_join(OriginTag::Ai, OriginTag::NetworkUntrusted), OriginTag::NetworkUntrusted);
/// ```
#[must_use]
pub const fn runtime_join(a: OriginTag, b: OriginTag) -> OriginTag {
    JOIN_TABLE_RT[a as usize][b as usize]
}

/// Runtime dominance: `true` iff `a` dominates `b` (a is at least as trusted
/// as b).
///
/// Derived from the join: `a` dominates `b` iff `join(a, b) == b` — joining
/// a more-trusted origin with a less-trusted one picks the less-trusted one
/// (widest-wins), so equality with `b` witnesses that `a >= b` in trust order.
#[must_use]
pub const fn dominates(a: OriginTag, b: OriginTag) -> bool {
    matches!(runtime_join(a, b) as u8, tag if tag == b as u8)
}

/// Public "lattice join" function usable by diagnostic / `DynProvenance`
/// combiners. Returns `None` if either input is the synthetic `Top` element
/// (encoded as `None`).
///
/// This is the function referenced in §3.4 of the design ("returns None for
/// Top").
///
/// # Returns
///
/// * `Some(tag)` when both inputs are concrete `OriginTag` and the join
///   resolves to a lattice element.
/// * `None` when either input is the synthetic `Top` element.
#[must_use]
pub const fn join(a: Option<OriginTag>, b: Option<OriginTag>) -> Option<OriginTag> {
    match (a, b) {
        (Some(x), Some(y)) => Some(runtime_join(x, y)),
        _ => None,
    }
}
