// The 4 branch-name string helpers (isAutoGeneratedCreatureBranchName,
// sanitizeBranchSlug, stripConfiguredBranchPrefix, humanizeBranchSlug) moved to
// the Rust branch-name-from-work core (orca-core): main drives them via napi
// (src/main/rust-branch-name-from-work.ts), the renderer via wasm
// (src/renderer/src/lib/git-wasm/branch-name-from-work.ts). buildBranchNamePrompt
// stays here on purpose — it's a pure prompt-copy template evaluated at module
// load (before the wasm render-gate), so it must not bind to a wasm fallback.

// Why: the work-derived branch name stays short on purpose — long, sentence-like
// branches read worse than the creature name they replace. Two-to-four words is
// the sweet spot the feature targets.
export const MAX_BRANCH_NAME_WORDS = 4
const MIN_BRANCH_NAME_WORDS = 2

export type BranchNameWorkContext = {
  /** The user's first prompt to the agent in this workspace. */
  firstPrompt: string
  /** The agent's first response, when it has already arrived. Optional because
   *  the rename fires as soon as work begins, before a reply may exist. */
  assistantMessage?: string
}

/**
 * Build the text-generation prompt that asks the configured agent to summarize
 * the work into a branch name. Kept in shared so the prompt is identical across
 * local and SSH generation targets.
 */
export function buildBranchNamePrompt(context: BranchNameWorkContext, customPrompt = ''): string {
  const sections = [
    'Generate a git branch name that summarizes the coding task described below.',
    'Rules:',
    `- Use between ${MIN_BRANCH_NAME_WORDS} and ${MAX_BRANCH_NAME_WORDS} words.`,
    '- Lowercase kebab-case only (words joined by single hyphens).',
    '- No slashes, no prefixes, no quotes, no trailing punctuation.',
    '- Describe the work itself, not the agent or the repository.',
    '- Output ONLY the branch name on a single line, nothing else.',
    '',
    'User request:',
    context.firstPrompt.trim()
  ]
  const assistant = context.assistantMessage?.trim()
  if (assistant) {
    sections.push('', "Agent's initial response:", assistant)
  }
  const prompt = customPrompt.trim()
  if (prompt) {
    sections.push('', 'Additional user prompt:', prompt)
  }
  return sections.join('\n')
}
