//! Parity dispatch for `orca_core::branch_name_from_work` vs
//! `src/shared/branch-name-from-work.ts`.

use orca_core::branch_name_from_work::{
    build_branch_name_prompt, humanize_branch_slug, is_auto_generated_creature_branch_name,
    sanitize_branch_slug, sanitize_branch_slug_default, BranchNameWorkContext,
};
use serde_json::{json, Value};

pub fn dispatch(function: &str, input: &Value) -> Value {
    match function {
        "isAutoGeneratedCreatureBranchName" => {
            let leaf = input.as_str().unwrap_or("");
            Value::Bool(is_auto_generated_creature_branch_name(leaf))
        }
        "sanitizeBranchSlug" => {
            let raw = input.get("raw").and_then(Value::as_str).unwrap_or("");
            // Absent maxWords mirrors the TS default parameter (MAX_BRANCH_NAME_WORDS).
            let slug = match input.get("maxWords").and_then(Value::as_u64) {
                Some(max_words) => sanitize_branch_slug(raw, max_words as usize),
                None => sanitize_branch_slug_default(raw),
            };
            Value::String(slug)
        }
        "humanizeBranchSlug" => {
            let slug = input.as_str().unwrap_or("");
            Value::String(humanize_branch_slug(slug))
        }
        "buildBranchNamePrompt" => {
            let context = input.get("context");
            let first_prompt = context
                .and_then(|c| c.get("firstPrompt"))
                .and_then(Value::as_str)
                .unwrap_or("")
                .to_string();
            // Missing key (TS undefined) reads as None, matching the optional field.
            let assistant_message = context
                .and_then(|c| c.get("assistantMessage"))
                .and_then(Value::as_str)
                .map(str::to_string);
            // Absent customPrompt mirrors the TS default empty-string parameter.
            let custom_prompt = input.get("customPrompt").and_then(Value::as_str).unwrap_or("");
            let ctx = BranchNameWorkContext {
                first_prompt,
                assistant_message,
            };
            Value::String(build_branch_name_prompt(&ctx, custom_prompt))
        }
        other => json!({ "__parity_error__": format!("unknown function {other}") }),
    }
}
