//! Per-module dispatch registry (generated by tools/parity integration).
use serde_json::Value;

pub mod agent_hook_endpoint_file;
pub mod agent_kind;
pub mod agent_notification_id;
pub mod agent_recognition;
pub mod agent_status_types;
pub mod agent_tab_title;
pub mod base_ref_search_result;
pub mod branch_name_from_work;
pub mod browser_screencast_protocol;
pub mod browser_search;
pub mod browser_viewport_presets;
pub mod commit_message_agent_spec;
pub mod commit_message_generation;
pub mod commit_message_host_key;
pub mod commit_message_models;
pub mod commit_message_plan;
pub mod commit_message_prompt;
pub mod contextual_tours;
pub mod cross_platform_path;
pub mod effective_upstream;
pub mod feature_education_telemetry;
pub mod feature_interactions;
pub mod feature_tips;
pub mod feature_wall_tour_depth;
pub mod fetch_error_classification;
pub mod git_cquoted_path;
pub mod git_history_log_parser;
pub mod push_target;
pub mod git_push_target;
pub mod git_remote_error;
pub mod git_upstream_status;
pub mod github_pr_merge_methods;
pub mod gitlab_pipeline_checks;
pub mod gitlab_projects;
pub mod hook_command_source_policy;
pub mod hosted_review_queue;
pub mod hosted_review_refs;
pub mod linear_links;
pub mod mcp;
pub mod mcp_env;
pub mod nacl_box;
pub mod native_file_drop;
pub mod nested_repo_telemetry;
pub mod network_proxy;
pub mod open_in_applications;
pub mod pairing;
pub mod pi_agent_kind;
pub mod pi_overlay_ui_settings;
pub mod project_groups;
pub mod protocol_compat;
pub mod pull_request_generation;
pub mod quick_open_filter;
pub mod repo_badge_color;
pub mod repo_clone_path;
pub mod repo_icon;
pub mod setup_runner_command;
pub mod setup_script_telemetry;
pub mod skill_metadata;
pub mod source_control_ai;
pub mod stable_pane_id;
pub mod synthetic_agent_title;
pub mod tab_title_resolution;
pub mod tailnet_address;
pub mod task_providers;
pub mod task_query;
pub mod terminal_fonts;
pub mod terminal_quick_commands;
pub mod terminal_stream;
pub mod terminal_surface_id;
pub mod terminal_tab_id;
pub mod tui_agent_selection;
pub mod tui_agent_startup;
pub mod uri_component;
pub mod workspace_cleanup;
pub mod workspace_name;
pub mod workspace_session_terminal_buffers;
pub mod workspace_statuses;
pub mod worktree;
pub mod worktree_id;
pub mod worktree_ownership;
pub mod wsl_paths;

/// Returns `None` when no Rust dispatch is registered for `module`.
pub fn dispatch(module: &str, function: &str, input: &Value) -> Option<Value> {
    match module {
        "agent-hook-endpoint-file" => Some(agent_hook_endpoint_file::dispatch(function, input)),
        "agent-kind" => Some(agent_kind::dispatch(function, input)),
        "agent-notification-id" => Some(agent_notification_id::dispatch(function, input)),
        "agent-recognition" => Some(agent_recognition::dispatch(function, input)),
        "agent-status-types" => Some(agent_status_types::dispatch(function, input)),
        "agent-tab-title" => Some(agent_tab_title::dispatch(function, input)),
        "base-ref-search-result" => Some(base_ref_search_result::dispatch(function, input)),
        "branch-name-from-work" => Some(branch_name_from_work::dispatch(function, input)),
        "browser-screencast-protocol" => Some(browser_screencast_protocol::dispatch(function, input)),
        "browser-search" => Some(browser_search::dispatch(function, input)),
        "browser-viewport-presets" => Some(browser_viewport_presets::dispatch(function, input)),
        "commit-message-agent-spec" => Some(commit_message_agent_spec::dispatch(function, input)),
        "commit-message-generation" => Some(commit_message_generation::dispatch(function, input)),
        "commit-message-host-key" => Some(commit_message_host_key::dispatch(function, input)),
        "commit-message-models" => Some(commit_message_models::dispatch(function, input)),
        "commit-message-plan" => Some(commit_message_plan::dispatch(function, input)),
        "commit-message-prompt" => Some(commit_message_prompt::dispatch(function, input)),
        "contextual-tours" => Some(contextual_tours::dispatch(function, input)),
        "cross-platform-path" => Some(cross_platform_path::dispatch(function, input)),
        "effective-upstream" => Some(effective_upstream::dispatch(function, input)),
        "feature-education-telemetry" => Some(feature_education_telemetry::dispatch(function, input)),
        "feature-interactions" => Some(feature_interactions::dispatch(function, input)),
        "feature-tips" => Some(feature_tips::dispatch(function, input)),
        "feature-wall-tour-depth" => Some(feature_wall_tour_depth::dispatch(function, input)),
        "fetch-error-classification" => Some(fetch_error_classification::dispatch(function, input)),
        "git-cquoted-path" => Some(git_cquoted_path::dispatch(function, input)),
        "git-history-log-parser" => Some(git_history_log_parser::dispatch(function, input)),
        "git-publish-target-status" => Some(push_target::dispatch(function, input)),
        "git-push-target" => Some(git_push_target::dispatch(function, input)),
        "git-remote-error" => Some(git_remote_error::dispatch(function, input)),
        "git-upstream-status" => Some(git_upstream_status::dispatch(function, input)),
        "github-pr-merge-methods" => Some(github_pr_merge_methods::dispatch(function, input)),
        "gitlab-pipeline-checks" => Some(gitlab_pipeline_checks::dispatch(function, input)),
        "gitlab-projects" => Some(gitlab_projects::dispatch(function, input)),
        "hook-command-source-policy" => Some(hook_command_source_policy::dispatch(function, input)),
        "hosted-review-queue" => Some(hosted_review_queue::dispatch(function, input)),
        "hosted-review-refs" => Some(hosted_review_refs::dispatch(function, input)),
        "linear-links" => Some(linear_links::dispatch(function, input)),
        "mcp" => Some(mcp::dispatch(function, input)),
        "mcp-env" => Some(mcp_env::dispatch(function, input)),
        "nacl-box" => Some(nacl_box::dispatch(function, input)),
        "native-file-drop" => Some(native_file_drop::dispatch(function, input)),
        "nested-repo-telemetry" => Some(nested_repo_telemetry::dispatch(function, input)),
        "network-proxy" => Some(network_proxy::dispatch(function, input)),
        "open-in-applications" => Some(open_in_applications::dispatch(function, input)),
        "pairing" => Some(pairing::dispatch(function, input)),
        "pi-agent-kind" => Some(pi_agent_kind::dispatch(function, input)),
        "pi-overlay-ui-settings" => Some(pi_overlay_ui_settings::dispatch(function, input)),
        "project-groups" => Some(project_groups::dispatch(function, input)),
        "protocol-compat" => Some(protocol_compat::dispatch(function, input)),
        "pull-request-generation" => Some(pull_request_generation::dispatch(function, input)),
        "quick-open-filter" => Some(quick_open_filter::dispatch(function, input)),
        "repo-badge-color" => Some(repo_badge_color::dispatch(function, input)),
        "repo-clone-path" => Some(repo_clone_path::dispatch(function, input)),
        "repo-icon" => Some(repo_icon::dispatch(function, input)),
        "setup-runner-command" => Some(setup_runner_command::dispatch(function, input)),
        "setup-script-telemetry" => Some(setup_script_telemetry::dispatch(function, input)),
        "skill-metadata" => Some(skill_metadata::dispatch(function, input)),
        "source-control-ai" => Some(source_control_ai::dispatch(function, input)),
        "stable-pane-id" => Some(stable_pane_id::dispatch(function, input)),
        "synthetic-agent-title" => Some(synthetic_agent_title::dispatch(function, input)),
        "tab-title-resolution" => Some(tab_title_resolution::dispatch(function, input)),
        "tailnet-address" => Some(tailnet_address::dispatch(function, input)),
        "task-providers" => Some(task_providers::dispatch(function, input)),
        "task-query" => Some(task_query::dispatch(function, input)),
        "terminal-fonts" => Some(terminal_fonts::dispatch(function, input)),
        "terminal-quick-commands" => Some(terminal_quick_commands::dispatch(function, input)),
        "terminal-stream-protocol" => Some(terminal_stream::dispatch(function, input)),
        "terminal-surface-id" => Some(terminal_surface_id::dispatch(function, input)),
        "terminal-tab-id" => Some(terminal_tab_id::dispatch(function, input)),
        "tui-agent-selection" => Some(tui_agent_selection::dispatch(function, input)),
        "tui-agent-startup" => Some(tui_agent_startup::dispatch(function, input)),
        "uri-component" => Some(uri_component::dispatch(function, input)),
        "workspace-cleanup" => Some(workspace_cleanup::dispatch(function, input)),
        "workspace-name" => Some(workspace_name::dispatch(function, input)),
        "workspace-session-terminal-buffers" => Some(workspace_session_terminal_buffers::dispatch(function, input)),
        "workspace-statuses" => Some(workspace_statuses::dispatch(function, input)),
        "worktree" => Some(worktree::dispatch(function, input)),
        "worktree-id" => Some(worktree_id::dispatch(function, input)),
        "worktree-ownership" => Some(worktree_ownership::dispatch(function, input)),
        "wsl-paths" => Some(wsl_paths::dispatch(function, input)),
        _ => None,
    }
}
