/**
 * Pre-computed POSIX shell launch config for the Rust daemon.
 *
 * Why client-side: the wrapper rcfiles (ZDOTDIR chain, bash --rcfile, the
 * OSC 777 shell-ready marker, attribution/CODEX_HOME restoration) are
 * generated by one TS module shared with LocalPtyProvider
 * (local-pty-shell-ready.ts). Re-implementing them in Rust would add a fourth
 * drifting copy, so the adapter computes the final program/args/env here and
 * ships them over the wire as `shellOverride`/`shellArgs`/`env`; the daemon
 * spawns them verbatim and runs the marker barrier
 * (rust/crates/orca-daemon/src/shell_ready_barrier.rs). See
 * docs/rust-migration/daemon-shell-launch.md.
 */
import {
  getAttributionShellLaunchConfig,
  getShellReadyLaunchConfig
} from '../providers/local-pty-shell-ready'
import { wrapShellSpawnForMacosTccAttribution } from '../providers/macos-tcc-login-shell'
import { seedPowerlevel10kWizardEnv } from '../pty/powerlevel10k-wizard-env'
import { recognizeAgentProcessFromCommandLine } from '../../shared/agent-process-recognition'
import {
  shouldUseShellReadyStartupDelivery,
  type StartupCommandDelivery
} from '../../shared/codex-startup-delivery'

export type DaemonShellLaunch = {
  /** The program to spawn — the resolved shell, or /usr/bin/login on macOS
   *  (TCC attribution wrap, mirroring the Node daemon's spawn seam). */
  shellOverride: string
  /** Verbatim spawn argv (wrapper args included). */
  shellArgs: string[]
  /** The session env with the wrapper's vars and the p10k wizard guard
   *  merged in. */
  env: Record<string, string>
}

// The launch modes that need the no-marker (attribution) wrapper even without
// a startup command — same gate as pty-subprocess.ts / local-pty-provider.ts.
const ATTRIBUTION_WRAPPER_ENV_KEYS = [
  'ORCA_ATTRIBUTION_SHIM_DIR',
  'ORCA_OPENCODE_CONFIG_DIR',
  'ORCA_MIMOCODE_HOME',
  'ORCA_OMP_STATUS_EXTENSION',
  'ORCA_CODEX_HOME',
  'ORCA_AGENT_TEAMS_SHIM_DIR'
] as const

export function buildPosixDaemonShellLaunch(opts: {
  shellOverride?: string
  env?: Record<string, string>
  envToDelete?: readonly string[]
  command?: string
  startupCommandDelivery?: StartupCommandDelivery
}): DaemonShellLaunch | null {
  // Windows keeps the Node daemon, which owns its own (ConPTY/WSL) launch
  // layer — this pre-compute is for the Unix-socket Rust daemon only.
  if (process.platform === 'win32') {
    return null
  }
  const env = opts.env ?? {}
  const shellPath = opts.shellOverride || env.SHELL || process.env.SHELL || '/bin/zsh'

  // Wrapper selection mirrors pty-subprocess.ts's POSIX branch: command
  // sessions get the marker wrapper (payload-bearing Codex too), markerless
  // Codex keeps the attribution wrapper for the startup-speed path, and plain
  // sessions only need a wrapper when a launch mode's env must survive rc files.
  const isCodexStartupCommand =
    recognizeAgentProcessFromCommandLine(opts.command)?.agent === 'codex'
  let shellLaunch: ReturnType<typeof getShellReadyLaunchConfig> | null = null
  if (opts.command && isCodexStartupCommand) {
    const shouldWaitForShellReady = shouldUseShellReadyStartupDelivery({
      command: opts.command,
      startupCommandDelivery: opts.startupCommandDelivery
    })
    shellLaunch = shouldWaitForShellReady
      ? getShellReadyLaunchConfig(shellPath)
      : getAttributionShellLaunchConfig(shellPath)
  } else if (opts.command) {
    shellLaunch = getShellReadyLaunchConfig(shellPath)
  } else if (ATTRIBUTION_WRAPPER_ENV_KEYS.some((key) => env[key])) {
    shellLaunch = getAttributionShellLaunchConfig(shellPath)
  }

  const mergedEnv: Record<string, string> = { ...opts.env, ...shellLaunch?.env }
  // Parity with pty-subprocess.ts / local-pty-provider.ts: block p10k's
  // first-run wizard, which would otherwise swallow the queued startup
  // command after the shell-ready barrier times out.
  seedPowerlevel10kWizardEnv(mergedEnv, { envToDelete: opts.envToDelete })
  // Plain login shell when no wrapper applies — terminals must keep
  // .zprofile/.zlogin env (parity with local-pty-provider.ts's ['-l']).
  const args = shellLaunch?.args ?? ['-l']
  // macOS: give the shell its own TCC identity via login(1), exactly like the
  // Node daemon's spawn seam (identity off-macOS). SHELL for the env(1)
  // re-assert resolves like the daemon child env would: overrides over main's.
  const wrapped = wrapShellSpawnForMacosTccAttribution(shellPath, args, {
    ...process.env,
    ...mergedEnv
  })
  return { shellOverride: wrapped.file, shellArgs: wrapped.args, env: mergedEnv }
}
