// Main-process branch-name string helpers, driven by the Rust orca-core via napi
// (their shared TS impls were deleted). One source of truth with the
// parity-proven Rust port. buildBranchNamePrompt stays in TS
// (src/shared/branch-name-from-work.ts) — a module-load prompt-copy template.
import { requireRustGitBinding } from './daemon/rust-git-addon'

function dispatch(fn: string, input: unknown): unknown {
  return JSON.parse(
    requireRustGitBinding().orcaDispatch('branch-name-from-work', fn, JSON.stringify(input ?? null))
  )
}

export function isAutoGeneratedCreatureBranchName(branchLeaf: string): boolean {
  return dispatch('isAutoGeneratedCreatureBranchName', branchLeaf) as boolean
}

export function sanitizeBranchSlug(raw: string, maxWords?: number): string {
  // JSON.stringify drops an `undefined` maxWords key, so an absent cap decodes to
  // Rust `None` and applies the MAX_BRANCH_NAME_WORDS default (the TS default param).
  return dispatch('sanitizeBranchSlug', { raw, maxWords }) as string
}

export function stripConfiguredBranchPrefix(
  slug: string,
  prefix: string | null | undefined
): string {
  return dispatch('stripConfiguredBranchPrefix', { slug, prefix }) as string
}

export function humanizeBranchSlug(slug: string): string {
  return dispatch('humanizeBranchSlug', slug) as string
}
