// TS dispatch for the branch-name-from-work parity module (a PARTIAL cutover).
// The 4 string helpers had their shared TS impls DELETED (the Rust orca-core is
// the sole impl — main via napi, renderer via wasm), so this adapter drives the
// SAME wasm for them: their TS-vs-Rust diff degenerates to wasm-vs-binary (drift
// between the two Rust entry points would still surface). buildBranchNamePrompt
// stays in TS (a module-load prompt-copy template), so it keeps comparing the
// live TS reference against the Rust port to catch prompt-copy drift.
import { gitWasmOracle } from './orca-git-wasm-oracle'
import {
  buildBranchNamePrompt,
  type BranchNameWorkContext
} from '../../../src/shared/branch-name-from-work'

function wasm(fn: string, input: unknown): unknown {
  return JSON.parse(
    gitWasmOracle().orcaDispatch('branch-name-from-work', fn, JSON.stringify(input ?? null))
  )
}

export function dispatch(fn: string, input: unknown): unknown {
  switch (fn) {
    case 'isAutoGeneratedCreatureBranchName':
    case 'sanitizeBranchSlug':
    case 'humanizeBranchSlug':
    case 'stripConfiguredBranchPrefix':
      return wasm(fn, input)
    case 'buildBranchNamePrompt': {
      const { context, customPrompt } = input as {
        context: BranchNameWorkContext
        customPrompt?: string
      }
      return customPrompt === undefined
        ? buildBranchNamePrompt(context)
        : buildBranchNamePrompt(context, customPrompt)
    }
    default:
      throw new Error(`unknown function ${fn}`)
  }
}
