// TS dispatch for the branch-name-from-work parity module: maps the shared
// vector function names to the real `src/shared/branch-name-from-work.ts`
// exports so the harness compares the live TS reference against the Rust port.

import {
  buildBranchNamePrompt,
  humanizeBranchSlug,
  isAutoGeneratedCreatureBranchName,
  sanitizeBranchSlug,
  type BranchNameWorkContext
} from '../../../src/shared/branch-name-from-work'

export function dispatch(fn: string, input: unknown): unknown {
  switch (fn) {
    case 'isAutoGeneratedCreatureBranchName':
      return isAutoGeneratedCreatureBranchName(input as string)
    case 'sanitizeBranchSlug': {
      const { raw, maxWords } = input as { raw: string; maxWords?: number }
      // Preserve the TS default when maxWords is absent, rather than forcing it.
      return maxWords === undefined ? sanitizeBranchSlug(raw) : sanitizeBranchSlug(raw, maxWords)
    }
    case 'humanizeBranchSlug':
      return humanizeBranchSlug(input as string)
    case 'buildBranchNamePrompt': {
      const { context, customPrompt } = input as {
        context: BranchNameWorkContext
        customPrompt?: string
      }
      return customPrompt === undefined
        ? buildBranchNamePrompt(context)
        : buildBranchNamePrompt(context, customPrompt)
    }
    default:
      throw new Error(`unknown function ${fn}`)
  }
}
