// Registry of TS parity dispatchers (generated by the tools/parity integration pass).
import { dispatch as agentHookEndpointFile } from './agent-hook-endpoint-file'
import { dispatch as agentKind } from './agent-kind'
import { dispatch as agentNotificationId } from './agent-notification-id'
import { dispatch as agentRecognition } from './agent-recognition'
import { dispatch as agentStatusTypes } from './agent-status-types'
import { dispatch as agentTabTitle } from './agent-tab-title'
import { dispatch as baseRefSearchResult } from './base-ref-search-result'
import { dispatch as branchNameFromWork } from './branch-name-from-work'
import { dispatch as browserScreencastProtocol } from './browser-screencast-protocol'
import { dispatch as browserSearch } from './browser-search'
import { dispatch as browserViewportPresets } from './browser-viewport-presets'
import { dispatch as commitMessageAgentSpec } from './commit-message-agent-spec'
import { dispatch as commitMessageGeneration } from './commit-message-generation'
import { dispatch as commitMessageHostKey } from './commit-message-host-key'
import { dispatch as commitMessageModels } from './commit-message-models'
import { dispatch as commitMessagePlan } from './commit-message-plan'
import { dispatch as commitMessagePrompt } from './commit-message-prompt'
import { dispatch as contextualTours } from './contextual-tours'
import { dispatch as crossPlatformPath } from './cross-platform-path'
import { dispatch as effectiveUpstream } from './effective-upstream'
import { dispatch as featureEducationTelemetry } from './feature-education-telemetry'
import { dispatch as featureInteractions } from './feature-interactions'
import { dispatch as featureTips } from './feature-tips'
import { dispatch as featureWallTourDepth } from './feature-wall-tour-depth'
import { dispatch as fetchErrorClassification } from './fetch-error-classification'
import { dispatch as gitCquotedPath } from './git-cquoted-path'
import { dispatch as gitHistoryLogParser } from './git-history-log-parser'
import { dispatch as gitPublishTargetStatus } from './git-publish-target-status'
import { dispatch as gitPushTarget } from './git-push-target'
import { dispatch as gitRemoteError } from './git-remote-error'
import { dispatch as gitUpstreamStatus } from './git-upstream-status'
import { dispatch as githubPrMergeMethods } from './github-pr-merge-methods'
import { dispatch as gitlabPipelineChecks } from './gitlab-pipeline-checks'
import { dispatch as gitlabProjects } from './gitlab-projects'
import { dispatch as hookCommandSourcePolicy } from './hook-command-source-policy'
import { dispatch as hostedReviewQueue } from './hosted-review-queue'
import { dispatch as hostedReviewRefs } from './hosted-review-refs'
import { dispatch as linearLinks } from './linear-links'
import { dispatch as mcp } from './mcp'
import { dispatch as mcpEnv } from './mcp-env'
import { dispatch as naclBox } from './nacl-box'
import { dispatch as nativeFileDrop } from './native-file-drop'
import { dispatch as nestedRepoTelemetry } from './nested-repo-telemetry'
import { dispatch as networkProxy } from './network-proxy'
import { dispatch as openInApplications } from './open-in-applications'
import { dispatch as pairing } from './pairing'
import { dispatch as piAgentKind } from './pi-agent-kind'
import { dispatch as piOverlayUiSettings } from './pi-overlay-ui-settings'
import { dispatch as projectGroups } from './project-groups'
import { dispatch as protocolCompat } from './protocol-compat'
import { dispatch as pullRequestGeneration } from './pull-request-generation'
import { dispatch as quickOpenFilter } from './quick-open-filter'
import { dispatch as repoBadgeColor } from './repo-badge-color'
import { dispatch as repoClonePath } from './repo-clone-path'
import { dispatch as repoIcon } from './repo-icon'
import { dispatch as setupRunnerCommand } from './setup-runner-command'
import { dispatch as setupScriptTelemetry } from './setup-script-telemetry'
import { dispatch as skillMetadata } from './skill-metadata'
import { dispatch as sourceControlAi } from './source-control-ai'
import { dispatch as stablePaneId } from './stable-pane-id'
import { dispatch as syntheticAgentTitle } from './synthetic-agent-title'
import { dispatch as tabTitleResolution } from './tab-title-resolution'
import { dispatch as tailnetAddress } from './tailnet-address'
import { dispatch as taskProviders } from './task-providers'
import { dispatch as taskQuery } from './task-query'
import { dispatch as terminalFonts } from './terminal-fonts'
import { dispatch as terminalQuickCommands } from './terminal-quick-commands'
import { dispatch as terminalStreamProtocol } from './terminal-stream-protocol'
import { dispatch as terminalSurfaceId } from './terminal-surface-id'
import { dispatch as terminalTabId } from './terminal-tab-id'
import { dispatch as tuiAgentSelection } from './tui-agent-selection'
import { dispatch as tuiAgentStartup } from './tui-agent-startup'
import { dispatch as uriComponent } from './uri-component'
import { dispatch as workspaceCleanup } from './workspace-cleanup'
import { dispatch as workspaceName } from './workspace-name'
import { dispatch as workspaceSessionTerminalBuffers } from './workspace-session-terminal-buffers'
import { dispatch as workspaceStatuses } from './workspace-statuses'
import { dispatch as worktree } from './worktree'
import { dispatch as worktreeId } from './worktree-id'
import { dispatch as worktreeOwnership } from './worktree-ownership'
import { dispatch as wslPaths } from './wsl-paths'

export type Dispatcher = (fn: string, input: unknown) => unknown

export const DISPATCH: Record<string, Dispatcher> = {
  'agent-hook-endpoint-file': agentHookEndpointFile,
  'agent-kind': agentKind,
  'agent-notification-id': agentNotificationId,
  'agent-recognition': agentRecognition,
  'agent-status-types': agentStatusTypes,
  'agent-tab-title': agentTabTitle,
  'base-ref-search-result': baseRefSearchResult,
  'branch-name-from-work': branchNameFromWork,
  'browser-screencast-protocol': browserScreencastProtocol,
  'browser-search': browserSearch,
  'browser-viewport-presets': browserViewportPresets,
  'commit-message-agent-spec': commitMessageAgentSpec,
  'commit-message-generation': commitMessageGeneration,
  'commit-message-host-key': commitMessageHostKey,
  'commit-message-models': commitMessageModels,
  'commit-message-plan': commitMessagePlan,
  'commit-message-prompt': commitMessagePrompt,
  'contextual-tours': contextualTours,
  'cross-platform-path': crossPlatformPath,
  'effective-upstream': effectiveUpstream,
  'feature-education-telemetry': featureEducationTelemetry,
  'feature-interactions': featureInteractions,
  'feature-tips': featureTips,
  'feature-wall-tour-depth': featureWallTourDepth,
  'fetch-error-classification': fetchErrorClassification,
  'git-cquoted-path': gitCquotedPath,
  'git-history-log-parser': gitHistoryLogParser,
  'git-publish-target-status': gitPublishTargetStatus,
  'git-push-target': gitPushTarget,
  'git-remote-error': gitRemoteError,
  'git-upstream-status': gitUpstreamStatus,
  'github-pr-merge-methods': githubPrMergeMethods,
  'gitlab-pipeline-checks': gitlabPipelineChecks,
  'gitlab-projects': gitlabProjects,
  'hook-command-source-policy': hookCommandSourcePolicy,
  'hosted-review-queue': hostedReviewQueue,
  'hosted-review-refs': hostedReviewRefs,
  'linear-links': linearLinks,
  'mcp': mcp,
  'mcp-env': mcpEnv,
  'nacl-box': naclBox,
  'native-file-drop': nativeFileDrop,
  'nested-repo-telemetry': nestedRepoTelemetry,
  'network-proxy': networkProxy,
  'open-in-applications': openInApplications,
  'pairing': pairing,
  'pi-agent-kind': piAgentKind,
  'pi-overlay-ui-settings': piOverlayUiSettings,
  'project-groups': projectGroups,
  'protocol-compat': protocolCompat,
  'pull-request-generation': pullRequestGeneration,
  'quick-open-filter': quickOpenFilter,
  'repo-badge-color': repoBadgeColor,
  'repo-clone-path': repoClonePath,
  'repo-icon': repoIcon,
  'setup-runner-command': setupRunnerCommand,
  'setup-script-telemetry': setupScriptTelemetry,
  'skill-metadata': skillMetadata,
  'source-control-ai': sourceControlAi,
  'stable-pane-id': stablePaneId,
  'synthetic-agent-title': syntheticAgentTitle,
  'tab-title-resolution': tabTitleResolution,
  'tailnet-address': tailnetAddress,
  'task-providers': taskProviders,
  'task-query': taskQuery,
  'terminal-fonts': terminalFonts,
  'terminal-quick-commands': terminalQuickCommands,
  'terminal-stream-protocol': terminalStreamProtocol,
  'terminal-surface-id': terminalSurfaceId,
  'terminal-tab-id': terminalTabId,
  'tui-agent-selection': tuiAgentSelection,
  'tui-agent-startup': tuiAgentStartup,
  'uri-component': uriComponent,
  'workspace-cleanup': workspaceCleanup,
  'workspace-name': workspaceName,
  'workspace-session-terminal-buffers': workspaceSessionTerminalBuffers,
  'workspace-statuses': workspaceStatuses,
  'worktree': worktree,
  'worktree-id': worktreeId,
  'worktree-ownership': worktreeOwnership,
  'wsl-paths': wslPaths,
}
