// Copyright 2026 The aterm Authors
// SPDX-License-Identifier: Apache-2.0

//! The two TOML records the updater reads/writes: the release-side **manifest**
//! (`aterm-appcast.toml`, an attached release asset, generated by
//! `tools/gen-appcast.sh`) and the local **ready marker** (`ready.toml`, written
//! last when staging completes — its presence is the sole "ready" signal).

use std::path::Path;

use serde::{Deserialize, Serialize};

/// The highest manifest `schema` version this build understands. A manifest
/// declaring a higher schema is from a newer format we can't safely interpret, so
/// we reject it (the client stays on its current build) rather than misread it.
pub const SUPPORTED_SCHEMA: u32 = 1;

/// The release manifest attached to a GitHub Release as `aterm-appcast.toml`.
/// Field set is kept in lockstep with `tools/gen-appcast.sh`.
#[derive(Debug, Clone, Deserialize)]
pub struct Manifest {
    /// Manifest format version (`gen-appcast.sh` emits `schema = 1`). Absent ⇒ 0.
    #[serde(default)]
    pub schema: u32,
    /// Human semver, e.g. `"0.2.0"`.
    pub version: String,
    /// Monotonic build number = `git rev-list --count HEAD`. The downgrade gate.
    pub build_number: u64,
    /// SHA-256 (lowercase hex) of the DMG asset.
    pub sha256: String,
    /// The DMG asset's file name within the release, e.g. `"aterm-0.2.0.dmg"`.
    pub dmg: String,
}

impl Manifest {
    /// Parse a manifest from TOML text, rejecting a schema this build is too old
    /// to understand.
    pub fn parse(text: &str) -> Result<Self, String> {
        let m: Manifest = toml::from_str(text).map_err(|e| format!("parse manifest: {e}"))?;
        if m.schema > SUPPORTED_SCHEMA {
            return Err(format!(
                "manifest schema {} is newer than supported ({SUPPORTED_SCHEMA}); upgrade aterm",
                m.schema
            ));
        }
        Ok(m)
    }
}

/// The local staging marker. Written atomically (temp + rename) AFTER the staged
/// bundle is fully materialized and verified, so a reader never sees a
/// half-staged update.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Ready {
    /// Build number of the staged bundle (must exceed the running build to apply).
    pub build_number: u64,
    /// Human semver of the staged bundle (for log lines).
    pub version: String,
    /// SHA-256 of the DMG the staged bundle came from (stage-time integrity record).
    pub dmg_sha256: String,
    /// Team ID recorded at stage time (re-checked against the signature at apply).
    pub team_id: String,
    /// RFC3339 UTC time the bundle was staged.
    pub staged_at: String,
}

impl Ready {
    /// Read + parse the marker, or `None` if absent/unparseable.
    pub fn read(path: &Path) -> Option<Self> {
        let text = std::fs::read_to_string(path).ok()?;
        toml::from_str(&text).ok()
    }

    /// Serialize to TOML text.
    pub fn to_toml(&self) -> Result<String, String> {
        toml::to_string(self).map_err(|e| format!("serialize ready marker: {e}"))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_a_manifest() {
        let m = Manifest::parse(
            r#"
            schema = 1
            version = "0.2.0"
            build_number = 1234
            sha256 = "abc123"
            dmg = "aterm-0.2.0.dmg"
            team_id = "TEAMID1234"
            commit = "deadbeef"
        "#,
        )
        .unwrap();
        assert_eq!(m.version, "0.2.0");
        assert_eq!(m.build_number, 1234);
        assert_eq!(m.dmg, "aterm-0.2.0.dmg");
    }

    /// Lock the contract with `tools/gen-appcast.sh`: the exact field set it emits
    /// (including the `'''` multiline `changelog` and extra keys) must parse, and
    /// the Manifest fields must read back correctly.
    #[test]
    fn parses_full_gen_appcast_shape() {
        let m = Manifest::parse(
            r#"
# Auto-generated by tools/gen-appcast.sh
schema = 1
version = "0.2.0"
build_number = 1234
commit = "deadbeefcafe"
dmg = "aterm-0.2.0.dmg"
sha256 = "ABC123"
min_os = "11.0"
team_id = "TEAMID1234"
pub_date = "2026-06-21T00:00:00Z"
url = "https://github.com/o/r/releases/download/v0.2.0/aterm-0.2.0.dmg"
changelog = '''
### Added
- a `thing` with "quotes" and # hashes
'''
"#,
        )
        .unwrap();
        assert_eq!(m.schema, 1);
        assert_eq!(m.version, "0.2.0");
        assert_eq!(m.build_number, 1234);
        assert_eq!(m.sha256, "ABC123");
        assert_eq!(m.dmg, "aterm-0.2.0.dmg");
    }

    /// A manifest from a newer format than this build understands is rejected
    /// (the client stays put) rather than silently misread.
    #[test]
    fn rejects_newer_schema() {
        let r = Manifest::parse(
            r#"
            schema = 99
            version = "9.0.0"
            build_number = 999999
            sha256 = "x"
            dmg = "aterm-9.0.0.dmg"
        "#,
        );
        assert!(r.is_err(), "a future schema must be rejected");
    }

    #[test]
    fn ready_round_trips() {
        let r = Ready {
            build_number: 9,
            version: "0.3.0".into(),
            dmg_sha256: "ff".into(),
            team_id: "T".into(),
            staged_at: "2026-06-21T00:00:00Z".into(),
        };
        let parsed: Ready = toml::from_str(&r.to_toml().unwrap()).unwrap();
        assert_eq!(parsed.build_number, 9);
        assert_eq!(parsed.version, "0.3.0");
    }
}
