/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_quickopenindex_free: (a: number, b: number) => void;
export const buildPullRequestFieldsPrompt: (a: number, b: number, c: number, d: number, e: number) => void;
export const computeLineStats: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => void;
export const countAdditionsInBuffer: (a: number, b: number) => number;
export const decodeGitCQuotedPath: (a: number, b: number, c: number) => void;
export const deriveGeneratedTabTitle: (a: number, b: number, c: number) => void;
export const detectPiAgentKindFromCommand: (a: number, b: number, c: number) => void;
export const formatSubmodulePushFailureDetail: (a: number, b: number, c: number) => void;
export const getLinearIssueWorkspaceName: (a: number, b: number, c: number, d: number, e: number) => void;
export const getLinkedWorkItemSuggestedName: (a: number, b: number, c: number) => void;
export const getLinkedWorkItemWorkspaceName: (a: number, b: number, c: number) => void;
export const getWorkspaceIntentName: (a: number, b: number, c: number) => void;
export const isNoUpstreamError: (a: number, b: number) => number;
export const normalizeGitErrorMessage: (a: number, b: number, c: number, d: number, e: number) => void;
export const parseGeneratedPullRequestFields: (a: number, b: number, c: number, d: number, e: number) => void;
export const parseGitHistoryLog: (a: number, b: number, c: number) => void;
export const parseNumstat: (a: number, b: number, c: number) => void;
export const parseStatusPorcelain: (a: number, b: number, c: number, d: number) => void;
export const parseWorktreeList: (a: number, b: number, c: number, d: number) => void;
export const planAgentBinary: (a: number, b: number, c: number, d: number, e: number) => void;
export const planCommitMessageGeneration: (a: number, b: number, c: number, d: number, e: number) => void;
export const quickopenindex_exactMatches: (a: number, b: number, c: number, d: number) => void;
export const quickopenindex_fileCount: (a: number) => number;
export const quickopenindex_new: (a: number, b: number) => number;
export const quickopenindex_rank: (a: number, b: number, c: number, d: number, e: number) => void;
export const slugifyForWorkspaceName: (a: number, b: number, c: number) => void;
export const stripCredentialsFromMessage: (a: number, b: number, c: number) => void;
export const terminalQuickCommandOp: (a: number, b: number, c: number, d: number, e: number) => void;
export const upstreamOnlyCommitsArePatchEquivalent: (a: number, b: number) => number;
export const validateGitPushTargetRules: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => void;
export const __wbindgen_add_to_stack_pointer: (a: number) => number;
export const __wbindgen_export: (a: number, b: number) => number;
export const __wbindgen_export2: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export3: (a: number, b: number, c: number) => void;
