// Renderer branch-name string helpers, driven by the Rust orca-core in the
// orca-git wasm module (their shared TS impls were deleted). buildBranchNamePrompt
// stays in TS (src/shared/branch-name-from-work.ts). The fallbacks run only on a
// wasm-load FAILURE (first paint is wasm-gated) and are chosen to not corrupt a
// name: the auto-generated check defaults to `false` so a failure never lets
// auto-rename overwrite a user-named branch; the slug transforms pass the input
// through in a benign form. (stripConfiguredBranchPrefix is main-only, so it has
// no renderer wrapper.)
import { isGitWasmReady } from './git-line-stats'
import { orcaDispatch } from './orca_git_wasm.js'

function op(fn: string, input: unknown): unknown | null {
  if (!isGitWasmReady()) return null
  return JSON.parse(orcaDispatch('branch-name-from-work', fn, JSON.stringify(input ?? null)))
}

export function isAutoGeneratedCreatureBranchName(branchLeaf: string): boolean {
  const r = op('isAutoGeneratedCreatureBranchName', branchLeaf) as boolean | null
  // Default to `false` so a wasm-load failure never treats a user-named branch as
  // auto-generated (which would let auto-rename overwrite it).
  return r ?? false
}

export function sanitizeBranchSlug(raw: string, maxWords?: number): string {
  const r = op('sanitizeBranchSlug', { raw, maxWords }) as string | null
  // Fall back to the lowercased-trimmed draft rather than '' so a wasm-load
  // failure degrades to a plausible slug instead of silently skipping the rename.
  return r ?? raw.trim().toLowerCase()
}

export function humanizeBranchSlug(slug: string): string {
  const r = op('humanizeBranchSlug', slug) as string | null
  // Pass the slug through unchanged on wasm-load failure; the sole caller already
  // falls back to the normalized branch when this is empty.
  return r ?? slug
}
